URL = "https?://[a-zA-Z0-9./?=_-]+"
Email = "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"
ip_address = "\\b(?:(?:25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\\.){3}(?:25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\\b"
credit_card = "\\b[0-9](?:[ -]?[0-9]){12,18}\\b"
ssn = "\\b\\d{3}-\\d{2}-\\d{4}\\b"
api_key = "\\b[A-Za-z0-9]{32,64}\\b"
pem_key = "-----BEGIN .*? KEY-----"
#file_path = "(\\/[\\w\\.\\-]+)+"
file_path = "(?:[a-zA-Z]:[\\/]|\\/)(?:[\\w.-]+[\\/])*[\\w.-]+\\.[a-zA-Z0-9]{1,6}"
guid = "\\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\\b"
mac = "([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})"
reg_path = "(HKEY_LOCAL_MACHINE|HKEY_CURRENT_USER|HKEY_CLASSES_ROOT|HKEY_USERS|HKEY_CURRENT_CONFIG)\\\\[\\w\\\\]+" 
sid = "S-1-\\d+-(\\d+-){1,14}\\d+" 
unc = "\\\\\\\\[A-Za-z0-9_.-]+\\\\[A-Za-z0-9$.~-]+"
aeon = "4[0-9AB][1-9A-HJ-NP-Za-km-z]{93}"
bitcoin = "^(bc1|[13])[a-zA-HJ-NP-Za-km-z]{25,39}$"
bitlocker = "[0-9]{8}-[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}"
bytecoin = "2[1-9A-HJ-NP-Za-km-z]{94}"
cardano = "^addr1[a-zA-HJ-NP-Za-km-z0-9]{58,}"
dashcoin = "^D[1-9A-HJ-NP-Za-km-z]{33}$"
dashcoin2 = "^(7|X)[1-9A-HJ-NP-Za-km-z]{33}$"
dogecoin = "^D{1}[5-9A-HJ-NP-U]{1}[1-9A-HJ-NP-Za-km-z]{32,34}$"
ethereum = "^0x[a-fA-F0-9]{40}$"
fantomcoin = "6[0-9AB][1-9A-HJ-NP-Za-km-z]{93}"
litecoin = "^[LM3][a-km-zA-HJ-NP-Z1-9]{26,33}$"
monero = "4[0-9AB][1-9A-HJ-NP-Za-km-z]{93}"
polkadot = "^1[a-km-zA-HJ-NP-Z1-9]{47}$"
ripple = "^r[0-9a-zA-Z]{24,34}$"
solana = "^[1-9A-HJ-NP-Za-km-z]{44}$"
sumokoin = "Sumo[0-9A-HJ-NP-Za-km-z]{94}"
zcash = "t1[a-zA-Z0-9]{33}"
